# Generated by Django 4.2.11 on 2024-03-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='data/book/<built-in function id>/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='data/book/<built-in function id>/'),
        ),
    ]
