# Generated by Django 4.2.11 on 2024-03-19 08:14

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_coverimage_alter_book_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.getImageURL),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to=home.models.getImageURL),
        ),
    ]
